apiVersion: apps/v1
kind: Deployment
metadata:
  name: minvid
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minvid
  template:
    metadata:
      labels:
        app: minvid
    spec:
      containers:
      - name: minvid
        image: registry.lan.buetow.org:30001/minvid:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: minvid-data
          mountPath: /app/data
      volumes:
      - name: minvid-data
        persistentVolumeClaim:
          claimName: minvid-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minvid
  name: minvid-service
  namespace: services
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: minvid
