apiVersion: apps/v1
kind: Deployment
metadata:
  name: minvid
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minvid
  template:
    metadata:
      labels:
        app: minvid
    spec:
      containers:
      - name: minvid
        image: ghcr.io/mariodian/minvid
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: minvid-data
          mountPath: /data
      volumes:
      - name: minvid-data
        persistentVolumeClaim:
          claimName: minvid-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minvid
  name: minvid-service
  namespace: services
spec:
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: minvid
