apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minvid-ingress
  namespace: services
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: services-forwarded-headers@kubernetescrd
spec:
  rules:
    - host: minvid.f3s.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minvid-service
                port:
                  number: 80
