apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-server
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-server
  template:
    metadata:
      labels:
        app: jellyfin-server
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.8.13
          ports:
            - containerPort: 8096
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-libraries
              mountPath: /media/libraries
            - name: jellyfin-data
              mountPath: /data
          volumes:
          - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-pvc
          - name: jellyfin-libraries
          persistentVolumeClaim:
            claimName: jellyfin-libraries-pvc
          - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin-server
  name: jellyfin-server
  namespace: services
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app: jellyfin-server
