# Jellyfin Traefik IngressRoute - HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingress
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.f3s.buetow.org`)
      kind: Rule
      services:
        - name: jellyfin-server
          port: 8096
  tls:
    certResolver: letsencrypt
---
# Redirect HTTP to HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingress-redirect
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jellyfin.f3s.buetow.org`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: jellyfin-server
          port: 8096
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: services
spec:
  redirectScheme:
    scheme: https
    permanent: true
